name: Update upstream submodule

on:
  pull_request:

permissions:
  pull-requests: write
  contents: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          # see: https://github.com/actions/checkout/issues/124
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Copy data files
        shell: bash
        run: cp upstream/data.txt src/data.txt
      - name: Configure git
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Update pull-request
        run: |
          if git diff -q; then
            git add .
            git commit -m "[dependabot skip] rebuild data files"
            git push
          else
            echo 'No changes detected'
          fi
